@startuml Solids

abstract BaseCollision

interface SolidCollision
interface Collision
interface UpdateableEntityCollision

SolidCollision --|> Collision

BlockCollision .u.|> SolidCollision
BlockCollision -u-|> BaseCollision 
BlockCollision "1" --> "1" BlockCollider

BrickCollision .u.|> SolidCollision
BrickCollision -u-|> BaseCollision 
BrickCollision "1" --> "1" BrickCollider

PipeCollision .u.|> SolidCollision
PipeCollision -u-|> BaseCollision 
PipeCollision "1" --> "1" PipeCollider

QuestionBlockCollision .u.|> SolidCollision
QuestionBlockCollision .u.|> UpdateableEntityCollision
QuestionBlockCollision -u-|> BaseCollision 
QuestionBlockCollision "1" --> "1" QuestionBlockCollider

@enduml