@startuml Invisibles

DelaterCollision -u-|> BaseCollision
DelaterCollision "1" --> "1" DelaterCollider

EmptyBlockCollision -u-|> BaseCollision
EmptyBlockCollision "1" --> "1" EmptyBlockCollider

LevelEndCollision -u-|> BaseCollision
LevelEndCollision "1" --> "1" LevelEndCollider

LoaderCollision -u-|> BaseCollision
LoaderCollision "1" --> "1" LoaderCollider

ScreenBorderCollision -u-|> BaseCollision
ScreenBorderCollision "1" --> "1" ScreenBorderCollider

ScreenDisplamentCollision -u-|> BaseCollision
ScreenDisplamentCollision "1" --> "1" ScreenBorderCollider

UnloaderCollision -u-|> BaseCollision
UnloaderCollision "1" --> "1" GraphicUnloaderCollider

@enduml