@startuml Entities

abstract class Body

Body "1" --> "1" GameGraphicElement

EmptyBlock -u-|> Body
EmptyBlock "1" --> "1" EmptyBlockCollider

FlagPole -u-|> Body
FlagPole "1" --> "1" FlagPoleCollider

ActionComparator .u.|> Comparator
@enduml
