@startuml PowerUps

abstract PowerUpCollider
abstract BaseCollider

interface BouncerCollider
interface UpdateableEntityCollider
interface PowerUp

FireFlowerCollider --|> PowerUpCollider
FireBallCollider --> FireFlower

GreenMushroomCollider --|> PowerUpCollider
GreenMushroomCollider --> GreenMushroom

SuperMushroomCollider --|> PowerUpCollider 
SuperMushroomCollider --> SuperMushroom

StarCollider --|> PowerUpCollider
StarCollider --> BouncerCollider
StarCollider --> Star

PowerUpCollider --|> BaseCollider 
PowerUpCollider --> UpdateableEntityCollider
PowerUpCollider --> PowerUp

@enduml