@startuml Updateables

interface Bouncer
interface UpdateableEntity

BouncerCollider --|> UpdateableEntityCollider
BouncerCollider --> Bouncer

UpdateableEntityCollider --|> Collider
UpdateableEntityCollider --> UpdateableEntity

@enduml