@startuml

abstract BaseCollision

DeleterCollision -u-|> BaseCollision
DeleterCollision "1" --> "1" DeleterCollider

EmptyBlockCollision -u-|> BaseCollision
EmptyBlockCollision "1" --> "1" EmptyBlockCollider

LevelEndCollision -u-|> BaseCollision
LevelEndCollision "1" --> "1" LevelEndCollider

LoaderCollision -u-|> BaseCollision
LoaderCollision "1" --> "1" LoaderCollider

ScreenBorderCollision -u-|> BaseCollision
ScreenBorderCollision "1" --> "1" ScreenBorderCollider

ScreenDisplacementCollision -u-|> BaseCollision
ScreenDisplacementCollision "1" --> "1" ScreenBorderCollider

UnloaderCollision -u-|> BaseCollision
UnloaderCollision "1" --> "1" GraphicUnloaderCollider

@enduml
