@startuml Solids

abstract Body
abstract UpdateableBody

interface UpdateableEntity

Block -u-|> Body
Block "1" --> "1" BlockCollider

Brick -u-|> Body
Brick "1" --> "1" BrickCollider

Pipe -u-|> Body
Pipe "1" --> "1" PipeCollider

QuestionBlock -u-|> UpdateableBody
QuestionBlock "1" --> "1" QuestionBlockCollider
QuestionBlock "1" --> "1" UpdateableEntity

Castle -u-|> Block

@enduml