@startuml Mario

FireMarioCollision -u-|> SuperMarioCollision
MarioCollision -u-|> UpdateableEntityCollision

DefaultMarioCollision .u.|> MarioCollision
DefaultMarioCollision -u-|> BaseCollision
DefaultMarioCollision "1" --> "1" MarioCollider

InvulnerableCollision .u.|> MarioCollision
InvulnerableCollision -u-|> BaseCollision
InvulnerableCollision "1" --> "1" MarioCollider

StarMarioCollision .u.|> MarioCollision
StarMarioCollision -u-|> BaseCollision
StarMarioCollision "1" --> "1" MarioCollider

SuperMarioCollision .u.|> MarioCollision
SuperMarioCollision -u-|> BaseCollision 
SuperMarioCollision "1" --> "1" MarioCollider

@enduml