@startuml Invisibles

DeleterCollider --|> BaseCollider

EmptyBlockCollider --|> SolidCollider
EmptyBlockCollider --> EmptyBlock

GraphicUnloaderCollider --|> BaseCollider

LevelEndCollider --> BaseCollider

LoaderCollider --|> BaseCollider

ScreenBorderCollider --|> BaseCollider
ScreenBorderCollider --> Direction

ScreenDisplacementCollider --|> BaseCollider
ScreenDisplacementCollider --> ScreenBorderCollider
ScreenDisplacementCollider --> LoaderCollider
ScreenDisplacementCollider --> GraphicUnloaderCollider
ScreenDisplacementCollider --> DeleterCollider

@enduml