@startuml
class CollisionsEngine 
CollisionsEngine --> CollisionsEngine
CollisionsEngine --> List
CollisionsEngine --> Set
CollisionsEngine --> Collider
Game ..|> WindowListener
Game ..|> KeyListener
class Game 
Game --> Game
Game --> Set
Game --> UpdatableEntity
Game --> Map
Game --> Integer
Game --> KeyStatus
Game --> Level
Game --> Mario
class GraphicEngine 
GraphicEngine --> GraphicEngine
GraphicEngine --> JFrame
GraphicEngine --> JPanel
GraphicEngine --> Set
GraphicEngine --> GraphicElement
enum KeyStatus 
class Level 
Level --> Duration
Level --> Image
class LevelReader 
LevelReader --> LevelReader
LevelReader --> Map
LevelReader --> Character
LevelReader --> EntityLoader
BaseCollider ..|> Collider
abstract class BaseCollider 
BaseCollider --> Rectangle
BaseCollider --> Vector2D
BaseCollider --> Vector2D
BlockCollider --|> BaseCollider
newpage
class BlockCollider 
BlockCollider --> Block
BlockCollider --> Rectangle
BlockCollider --> Point
interface Collider 
enum Direction 
GoombaCollider --|> BaseCollider
GoombaCollider ..|> UpdateableEntityCollider
class GoombaCollider 
GoombaCollider --> Goomba
KoopaTroopaCollider --|> BaseCollider
KoopaTroopaCollider ..|> UpdateableEntityCollider
class KoopaTroopaCollider 
KoopaTroopaCollider --> KoopaTroopa
LoaderCollider --|> BaseCollider
class LoaderCollider 
MarioCollider --|> BaseCollider
MarioCollider ..|> UpdateableEntityCollider
class MarioCollider 
MarioCollider --> Mario
ScreenBorderCollider --|> BaseCollider
class ScreenBorderCollider 
ScreenBorderCollider --> Direction
ScreenDisplacementCollider --|> BaseCollider
class ScreenDisplacementCollider 
ScreenDisplacementCollider --> ScreenBorderCollider
ScreenDisplacementCollider --> ScreenBorderCollider
ScreenDisplacementCollider --> LoaderCollider
SpinyCollider --|> BaseCollider
SpinyCollider ..|> UpdateableEntityCollider
class SpinyCollider 
SpinyCollider --> Spiny
SuperMushroomCollider --|> BaseCollider
SuperMushroomCollider ..|> UpdateableEntityCollider
class SuperMushroomCollider 
SuperMushroomCollider --> SuperMushroom
UpdateableEntityCollider --|> Collider
interface UpdateableEntityCollider 
class Vector2D 
Vector2D --> Point
Vector2D --> Point
enum Axis 
BlockCollision ..|> Collision
class BlockCollision 
BlockCollision --> BlockCollider
interface Collision 
GoombaCollision ..|> UpdateableEntityCollision
class GoombaCollision 
GoombaCollision --> GoombaCollider
KoopaTroopaCollision ..|> UpdateableEntityCollision
class KoopaTroopaCollision 
KoopaTroopaCollision --> KoopaTroopaCollider
LoaderCollision ..|> Collision
class LoaderCollision 
LoaderCollision --> LoaderCollider
MarioCollision ..|> UpdateableEntityCollision
class MarioCollision 
MarioCollision --> MarioCollider
ScreenBorderCollision ..|> Collision
class ScreenBorderCollision 
ScreenBorderCollision --> ScreenBorderCollider
ScreenDisplacementCollision ..|> Collision
class ScreenDisplacementCollision 
ScreenDisplacementCollision --> ScreenDisplacementCollider
SpinyCollision ..|> UpdateableEntityCollision
class SpinyCollision 
SpinyCollision --> SpinyCollider
SuperMushroomCollision ..|> UpdateableEntityCollision
newpage
class SuperMushroomCollision 
SuperMushroomCollision --> SuperMushroomCollider
UpdateableEntityCollision --|> Collision
interface UpdateableEntityCollision 
BlockLoader ..|> EntityLoader
class BlockLoader 
interface EntityLoader 
GoombaLoader ..|> EntityLoader
class GoombaLoader 
KoopaTroopaLoader ..|> EntityLoader
class KoopaTroopaLoader 
MarioLoader ..|> EntityLoader
class MarioLoader 
SpinyLoader ..|> EntityLoader
class SpinyLoader 
SuperMushroomLoader ..|> EntityLoader
class SuperMushroomLoader 
BaseEntity ..|> Entity
abstract class BaseEntity 
BaseEntity --> Collider
BaseEntity --> GraphicElement
BaseUpdatableEntity --|> BaseEntity
BaseUpdatableEntity ..|> UpdatableEntity
abstract class BaseUpdatableEntity 
Block --|> BaseEntity
newpage
class Block 
Enemy --|> UpdatableEntity
interface Enemy 
interface Entity 
Goomba --|> BaseUpdatableEntity
Goomba ..|> Enemy
class Goomba 
Goomba --> Velocidad
KoopaTroopa --|> BaseUpdatableEntity
KoopaTroopa ..|> Enemy
class KoopaTroopa 
Mario --|> BaseUpdatableEntity
class Mario 
Mario --> Direction
Spiny --|> BaseUpdatableEntity
Spiny ..|> Enemy
class Spiny 
SuperMushroom --|> BaseUpdatableEntity
class SuperMushroom 
UpdatableEntity --|> Entity
interface UpdatableEntity 
GameGraphicElement ..|> GraphicElement
class GameGraphicElement 
GameGraphicElement --> Entity
GameGraphicElement --> JLabel
GameGraphicElement --> ImageIcon
GameGraphicElement --> Rectangle
interface GraphicElement 
@enduml
