@startuml
' # JUEGO #
'
class Game <<Singleton>>
class Menu <<Singleton>>
class GameEntity
class CollisionsEngine <<Singleton>>
class GraphicEngine <<Singleton>>
class LevelReader <<Singleton>>
Game "1" --> "1" Menu
Game "1" *-- "1" Level
Game "1" --> "1" Mario
Game "1" *-- "1" GraphicEngine
Game "1" *-- "1" CollisionsEngine
Game "1" --> "1" Ranking
Game "1" -- "1" LevelReader
Game "1" --> "0..*" Entity
LevelReader "1" -- CollisionsEngine
LevelReader "1" -- GraphicEngine
LevelReader "1" -- Mario
LevelReader "1" -- GameEntity
GameEntity ..|> Entity

' # ENTIDAD #
'
interface Entity
Entity "1" ---> "0..*" GraphicElement
Entity "1" --- "0..*" Collider

' # GRAFICA #
'
interface GraphicElement
class GameGraphicElement
class SpriteFactory <<Singleton>>
class Sprite <<Flyweight>>
GameGraphicElement .u.|> GraphicElement
Sprite "0..*" --o "1" SpriteFactory
GraphicElement o-- "0..*" Sprite
GraphicElement "1..*" -- "1" GraphicEngine
GraphicElement "1" --> "1" Position

' # COLLISIONS #
'
interface Collider
abstract class GameCollider
Collider "1" --> "0..1" Position
Collider "1..*" -- "1" CollisionsEngine
GameCollider ..|> Collider
MarioCollider .u.|> GameCollider
EnemyCollider .u.|> GameCollider
PlatformCollider .u.|> GameCollider
CoinCollider .u.|> GameCollider
PowerUpCollider .u.|> GameCollider
FireBallCollider .u.|> GameCollider

' # PERSONAJE #
'
interface MarioState <<Command>>
class Mario 
Mario ...|> Entity
Mario "1" -- "0..*" MarioState
Super .u.|> MarioState
Fire .u.|> MarioState
Invincible .u.|> MarioState
interface EnemyCollision <<Strategy>>
interface BrickCollision <<Strategy>>
class FireBallThrower
class Croucher
FireBallThrower ..|> Entity
Croucher ..|> Entity
Mario <-- FireBallThrower
Mario <-- Croucher
DefaultBrickCollision .u.|> BrickCollision
BreakBrickCollision .u.|> BrickCollision
DefaultEnemyCollision .u.|> EnemyCollision
SuperEnemyCollision .u.|> EnemyCollision
InvincibleEnemyCollision .u.|> EnemyCollision
Mario o-d- "1" EnemyCollision
Mario o-d- "1" BrickCollision
Mario --> Position

newpage

' # NIVEL #
'
interface Platform
interface Enemy
interface PowerUp
class Coin
Platform ...u.|> Entity
Enemy ..u.|> Entity
PowerUp ..u.|> Entity
Coin .u.|> Entity

' # ENEMIGOS #
'

Goomba .u.|> Enemy
KoopaTroopa .u.|> Enemy
KoopaTroopa "1" o-- "1" Shell
PiranhaPlant .u.|> Enemy
Lakitu .u.|> Enemy
Spiny .u.|> Enemy
BuzzyBeattle .u.|> Enemy
Pipe --> "0..1" PiranhaPlant

' # PLATAFORMAS #
'
Void .u.|> Platform
SolidBlock .u.|> Platform
SolidBrick -u-|> SolidBlock
QuestionBlock -u-|> SolidBlock
Pipe .u.|> Platform

' # POWERUPS #
'
SuperMushroom .u.|> PowerUp
FireFlower .u.|> PowerUp
Star .u.|> PowerUp
GreenMushroom .u.|> PowerUp

' # PROYECTIL #
'
interface Proyectile
Proyectile .u.|> Entity
FireBall .u.|> Proyectile
Star .u.|> Proyectile

' # MOVABLE #
interface Movable
Enemy .u.|> Movable
GreenMushroom .u.|> Movable
SuperMushroom .u.|> Movable

' # FORMATTING #
'
@enduml
