@startuml
' TODO: agregar constructores y getters y setters (habría que preguntar si podemos evitar algunos getters y setters en pos de encapsulamiento)
'
interface Movable{
    +move()
    +changeDirection()
}

interface Enemy { 
    +recieveDamage() 
    +getPoints(): int
}

Enemy .u[hidden].|> Movable


class BuzzyBeattle{
    #graphicElement: GraphicElement
    #pos: Position
    # {static}speedX: int
    +BuzzyBeattle(ge: GraphicElement, pos: Position)     
}
class Spiny{
    #graphicElement: GraphicElement
    #pos: Position
    # {static}speedX: int
    +Spiny(ge: GraphicElement, pos: Position)         
}
class Lakitu{
    #graphicElement: GraphicElement
    #pos: Position
    # {static}speedX: int
    +Lakitu(ge: GraphicElement, pos: Position)      
}
class PiranhaPlant{
    #graphicElement: GraphicElement
    #pos: Position
    # {static}speedX: int
    +PiranhaPlant(ge: GraphicElement, pos: Position)    
}
class KoopaTroopa{
    #graphicElement: GraphicElement
    #pos: Position
    # {static}speedX: int
    +KoopaTroopa(ge: GraphicElement, pos: Position)
}

class Goomba{
    #graphicElement: GraphicElement
    #pos: Position
    # {static}speedX: int
    +Goomba(ge: GraphicElement, pos: Position)
}


interface PowerUp {
    +apply(character: Character)
}

class GreenMushroom{
    #graphicElement: GraphicElement
    GreenMushroom(gE: GraphicElement)
}

interface Proyectile

class FireBall{
    #pos: Position
    #graphicElement: GraphicElement
    # {static}speedX: int
}

class Pipe {
    #piranha: PiranhaPlant
    #graphicElement: GraphicElement
    +Pipe(p: PiranhaPlant, gE: GraphicElement)

}

class SolidBrick {
    #graphicElement: GraphicElement
    +SolidBrick(gE: GraphicElement)
    +break()
}

class QuestionBlock {
    #coin: Coin
    #PowerUp: PowerUp
    +QuestionBlock(pW: PowerUp, coin: Coin)
}

class Coin{
    #graphicElement: GraphicElement
    +Coin(gE: GraphicElement)
}

class FireFlower{
    #graphicElement: GraphicElement
    +FireFlower(gE: GraphicElement) 
}
class SuperMushroom{
    #graphicElement: GraphicElement
    +SuperMushroom(gE: GraphicElement)     
}
class Star{
    #graphicElement: GraphicElement
    +Star(gE: GraphicElement)      
}
class GreenMushroom{
    #graphicElement: GraphicElement
    +GreenMushroom(gE: GraphicElement)      
}

SolidBlock .u[hidden].|> Platform
SolidBrick -u[hidden]-|> SolidBlock
QuestionBlock -u[hidden]-|> SolidBlock
Pipe .u[hidden].|> Platform
Platform -l[hidden]- Movable
Movable -l[hidden]- PowerUp
@enduml
