@startuml

class Personaje{
    #estado : Estado
    +mover(direccion : String)
    +saltar()
    ' vacio
    +lanzarProyectil()
    +setEstado(estado : Estado)
    +getEstado() : Estado
}

class Sprite{
    #imagen : Image
    +draw(int x, int y)
    +setImagen(image : Image)
    +getImagen() : Image
}

class Nivel{
    #plataformas : List<Plataforma>
    #enemigos : List<Enemigo>
    #powerUps : List<PowerUp>
    #monedas : List<Moneda>
    #puntaje : int
    +cargarNivel()
    +getPuntaje() : int
    +setPuntaje(puntaje : int)
}

class Proyectil{
    +mover()
}

class PowerUp{
    +aplicarEfecto(p : Personaje)
}

class Enemigo{
    +mover(direccion : String)
}

class Tuberia{
    #piranhaPlant : PiranhaPlant
}

class BloquePregunta{
    #contenido : AlteradorPuntaje
}

class Menu{
    +mostrarModos()
    +seleccionarModo()
    mostrarRanking()
}

' # Podemos agregar una clase Jugador donde se guarda el nombre y puntaje (para el ranking) #

class Jugador{
    #nombre : String
    #puntaje : int
}

class Juego{
    #niveles : List<Nivel>
    #personaje : Personaje
    #engine : Engine
    #ranking : Jugador[]
    #modo : ??
}

class Engine {
    #chunks: [][]ElementoGrafico
    +notify()
    +load()
}

interface ElementoGrafico {
    +draw()
    +handleCollision(ElementoGrafico)
    +load()
}

@enduml
