' # JUEGO #
'
Juego "1" --> "1" Menu
Juego "1" *-l- "3" Nivel
' TODO: Preguntar personaje o mario?
Juego "1" --> "1" Personaje
Juego "1" *-d- "1" Engine
Juego "1" -r-> "1" Ranking

' # PERSONAJE #
'
interface Estado
class Personaje implements ElementoGrafico
Personaje -d-> "0..*" Estado
class Normal implements Estado
class Super implements Estado
class Fuego implements Estado
class Invulnerable implements Estado

' # GRAFICA #
'
interface ElementoGrafico
class Sprite
ElementoGrafico o-l- "0..*" Sprite

' # NIVEL #
'
interface AlteradorPuntaje
interface Plataforma implements ElementoGrafico
' TODO: Preguntar 0 o 1 a muchos?
Nivel "1" -d- "0..*" Plataforma
Nivel "1" -d- "0..*" AlteradorPuntaje
interface Enemigo implements AlteradorPuntaje, ElementoGrafico
class Moneda implements AlteradorPuntaje, ElementoGrafico
interface PowerUp implements AlteradorPuntaje, ElementoGrafico

' # ENEMIGOS #
'
class Goomba implements Enemigo
class KoopaTroopa implements Enemigo
class PiranhaPlant implements Enemigo
class Lakitu implements Enemigo
class Spiny implements Enemigo
class BuzzyBeattle implements Enemigo
Tuberia --> "0..1" PiranhaPlant

' # PLATAFORMAS #
'
class Vacio implements AlteradorPuntaje, Plataforma
class BloqueSolido implements Plataforma
class LadrilloSolido extends BloqueSolido
class BloquePregunta extends BloqueSolido
class Tuberia implements Plataforma

' # POWERUPS #
'
class SuperChampinion implements PowerUp
class FlorFuego implements PowerUp
class Estrella implements PowerUp
class ChampinionVerde implements PowerUp

' # PROYECTIL #
'
interface Proyectil implements ElementoGrafico
class BolaFuego implements Proyectil

' # DESLIZABLE #
'
interface Deslizable implements ElementoGrafico
class Caparazon implements Deslizable
KoopaTroopa "1" o-- "1" Caparazon

' # FORMATTING #
'
Nivel -l[hidden]- ElementoGrafico
Enemigo -u[hidden]- FlorFuego

