@startuml
class DeleterCollision {
   #collider: DeleterCollider
   #DeleterCollision()
   +DeleterCollision(d: DeleterCollider)
   +getCollider(): DeleterCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

class EmptyBlockCollision {
   #collider: EmptyBlockCollider
   +EmptyBlockCollision(c: EmptyBlockCollider)
   +getCollider(): EmptyBlockCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

class LevelEndCollision {
   #collider: LevelEndCollider
   +LevelEndCollision(l: LevelEndCollider)
   +getCollider(): LevelEndCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

class LoaderCollision {
   #loader: LoaderCollider
   +LoaderCollision(l: LoaderCollider)
   +getCollider(): LoaderCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

class ScreenBorderCollision {
   #collider: ScreenBorderCollider
   +ScreenBorderCollision(c: ScreenBorderCollider)
   +getCollider(): ScreenBorderCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

class ScreenDisplacementCollision {
   #collider: ScreenDisplacementCollider
   +ScreenDisplacementCollision(c: ScreenDisplacementCollider)
   +getCollider(): ScreenDisplacementCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

class UnloaderCollision {
   #unloader: GraphicUnloaderCollider
   +UnloaderCollision(l: GraphicUnloaderCollider)
   +getCollider(): GraphicUnloaderCollider 
   +collide(c: BlockCollider, a: Axis)
   +collide(c: ScreenDisplacementCollider, a: Axis)
   +collide(c: ScreenBorderCollider, a: Axis)
   +collide(c: GoombaCollider, a: Axis)
   +collide(c: SpinyCollider, a: Axis)
   +collide(c: KoopaTroopaCollider, a: Axis)
   +collide(c: SuperMushroomCollider, a: Axis)
   +collide(c: LoaderCollider, a: Axis)
   +collide(c: BrickCollider, a: Axis)
   +collide(c: PipeCollider, a: Axis)
   +collide(c: QuestionBlockCollider, a: Axis)
   +collide(c: CoinCollider, a: Axis)
   +collide(c: GraphicUnloaderCollider, a: Axis)
   +collide(c: DeleterCollider, a: Axis)
   +collide(c: colliders.updateables.enemies.LakituCollider, a: Axis)
   +collide(c: BuzzyBeetleCollider, a: Axis)
   +collide(c: PiranhaPlantCollider, a: Axis)
   +collide(c: FireFlowerCollider, a: Axis)
   +collide(c: StarMarioCollider, a: Axis)
   +collide(c: GreenMushroomCollider, a: Axis)
   +collide(c: SuperMarioCollider, a: Axis)
   +collide(c: DefaultMarioCollider, a: Axis)
   +collide(c: EmptyBlockCollider, a: Axis)
   +collide(c: LevelEndCollider, a: Axis)
   +collide(c: InvulnerableCollider, a: Axis)
   +collide(c: FlagPoleCollider, a: Axis)
   +collide(c: FireMarioCollider, a: Axis)
   +collide(c: FireBallCollider, a: Axis)
   +collide(c: ModeSwitcherCollider, a: Axis)
   +collide(c: LanguageSwitcherCollider, a: Axis)
   +collide(c: StarCollider, a: Axis)
   +collide(c: RankingShowCollider, a: Axis)
}

@enduml
