@startuml
Game ..|> WindowListener
Game ..|> KeyListener
Game --> Game
Game --> UpdatableEntity
Game --> KeyStatus
Game --> Stats
Game --> GameOverScreen
Game --> RankingManager
Game --> Map
Game --> List
Game --> Set
class Game
CollisionsEngine --> CollisionsEngine
CollisionsEngine --> Collider
CollisionsEngine --> List
CollisionsEngine --> Set
class CollisionsEngine
GraphicEngine --> GraphicEngine
GraphicEngine --> JFrame
GraphicEngine --> JLayeredPane
GraphicEngine --> GraphicElement
GraphicEngine --> GameGraphicElement
GraphicEngine --> Set
GraphicEngine --> Integer
class GraphicEngine
LanguageConfiguration --> LanguageConfiguration
LanguageConfiguration --> Properties
class LanguageConfiguration
LevelReader --> LevelReader
LevelReader --> Map
LevelReader --> Character
LevelReader --> EntityLoader
class LevelReader
interface LevelStatsObserver
LevelTimer --> Timer
class LevelTimer
RankingManager --> ScoreEntry
RankingManager --> List
class RankingManager
SoundManager --> SoundManager
SoundManager --> Clip
SoundManager --> Map
class SoundManager
Stats --> List
Stats --> LevelTimer
Stats --> LevelStatsObserver
class Stats
StatsPanel --|> JPanel
StatsPanel --> JLabel
class StatsPanel
@enduml
