@startuml

interface Collision
interface SolidCollision
interface UpdateableEntityCollision
interface UpdateableEntityCollider
interface ShellEnemyCollision
interface EnemyCollision

abstract BaseCollision


'Dentro de collisions
BaseCollision --|> Collision

CoinCollision --|> BaseCollision 
CoinCollision --> UpdateableEntityCollision
CoinCollision --> coinCollider

FlagPoleCollision --|> BaseCollision
FlagPoleCollision --> FlagPoleCollider

LanguageSwitcherCollision --|> BaseCollision
LanguageSwitcherCollision --> UpdateableEntityCollision
LanguageSwitcherCollision --> LanguageSwitcherCollider

ModeSwitcherCollision --|> BaseCollision
ModeSwitcherCollision --> UpdateableEntityCollision
ModeSwitcherCollision --> ModeSwitcherCollider

RankingShowCollision --|> BaseCollision 
RankingShowCollision --> UpdateableEntityCollision
RankingShowCollision --> RankingShowCollider

'Dentro de invisibles

DelaterCollision --|> BaseCollision
DelaterCollision --> DelaterCollider

EmptyBlockCollision --|> BaseCollision
EmptyBlockCollision --> EmptyBlockCollider

LevelEndCollision --|> BaseCollision
LevelEndCollision --> LevelEndCollider

LoaderCollision --|> BaseCollision
LoaderCollision --> LoaderCollider

ScreenBorderCollision --|> BaseCollision
ScreenBorderCollision --> ScreenBorderCollider

ScreenDisplamentCollision --|> BaseCollision
ScreenDisplamentCollision --> ScreenBorderCollider

UnloaderCollision --|> BaseCollision
UnloaderCollision --> GraphicUnloaderCollider

'Dentro de Solids

BlockCollision --|> BaseCollision 
BlockCollision --> SolidCollision
BlockCollision --> BlockCollider

BrickCollision --|> BaseCollision 
BrickCollision --> SolidCollision
BrickCollision --> BrickCollider

PipeCollision --|> BaseCollision 
PipeCollision --> SolidCollision
PipeCollision --> PipeCollider

QuestionBlockCollision --|> BaseCollision 
QuestionBlockCollision --> SolidCollision
QuestionBlockCollision --> UpdateableEntityCollision
QuestionBlockCollision --> QuestionBlockCollider

SolidCollision --|> Collision


'Dentro de Updeteables

BouncerCollision --|> UpdateableEntityCollision
BouncerCollision --> BouncerCollider

FireBallCollision --|> BaseCollision
FireBallCollision --> BouncerCollision
FireBallCollision --> FireBallCollider

UpdateableEntityCollision --|> Collision
UpdateableEntityCollision --> UpdateableEntityCollider

' Dentro de enemigos

BuzzyBeetleCollision --|> BaseCollision
BuzzyBeetleCollision --> ShellEnemyCollision
BuzzyBeetleCollision --> BuzzyBeetleCollider

EnemyCollision --|> UpdateableEntityCollision

GoombaCollision --|> BaseCollision 
GoombaCollision --> EnemyCollision
GoombaCollision --> GoombaCollider

KoopaTroopa --|> BaseCollision
KoopaTroopa --> ShellEnemyCollision
KoopaTroopa --> KoopaTroopaCollider

LakituCollision --|> BaseCollision 
LakituCollision --> EnemyCollision
LakituCollision --> LakituCollider

PiranhaPlantCollision --|> BaseCollision
PiranhaPlantCollision --> EnemyCollision
PiranhaPlantCollision --> PiranhaPlantCollider

ShellEnemyCollision --|> EnemyCollision

SpinyCollision --|> BaseCollision
SpinyCollision --> EnemyCollision
SpinyCollision --> SpinyCollider

'Dentro de Mario

DefaultMarioCollision --|> BaseCollision
DefaultMarioCollision --> MarioCollision
DefaultMarioCollision --> MarioCollider

FireMarioCollision --|> SuperMarioCollision

InvulnerableCollision --|> BaseCollision
InvulnerableCollision --> MarioCollision
InvulnerableCollision --> MarioCollider

MarioCollision --|> UpdateableEntityCollision
MarioCollision --> MarioCollider

StarMarioCollision --|> BaseCollision
StarMarioCollision --> MarioCollision
StarMarioCollision --> MarioCollider

SuperMarioCollision --|> BaseCollision 
SuperMarioCollision --> MarioCollision
SuperMarioCollision --> MarioCollider

'Dentro de PowerUp

FireFlowerCollision --|> BaseCollision
FireFlowerCollision --> PowerUpCollision
FireFlowerCollision --> FireFlowerCollider

GreenMushroomCollision --|> BaseCollision
GreenMushroomCollision --> PowerUpCollision
GreenMushroomCollision --> GreenMushroomCollider

PowerUpCollision --|> UpdateableEntityCollision
PowerUpCollision --> PowerUpCollider

StarCollision --|> BaseCollision
StarCollision --> PowerUpCollision
StarCollision --> BouncerCollision
StarCollision --> StarCollider

SuperMushroomCollision --|> BaseCollision
SuperMushroomCollision --> PowerUpCollision
SuperMushroomCollision --> SuperMarioCollider
@enduml